### PR TITLE
Expose type definitions in package.json

### PR DESCRIPTION
**Pull request by qelix**
As discussed in #5 :)

I haven't actually tested it, as I haven't ever published anything to npm, but I'm pretty sure it should work fine.

### CODE REVIEW

**Comment by maciekgrzybek** [comment]
Thanks for PR :) I'll take a look but I'm afraid you got to the same place I did :D I'll let you know ASAP :)

**Comment by qelix** [comment]
Any chance you'll take a look at this soon? :)  When I said I hadn't tested it, I meant that I haven't tested publishing the package to npm. The type definitions generate just fine.

**Comment by maciekgrzybek** [comment]
Hey @qelix I'm terribly sorry about it I had busy few weeks (moving to a different country). I will try and sort it out ON Wednesday. Happy to pair on this if you like :)

**Comment by maciekgrzybek** [comment]
Unfortunately, that doesn't work, I've spent few days on it and it still doesn't work (it generates the definition file but that doesn't help as we still need to define custom actions, something like this:
```
declare namespace svelte.JSX {
  interface HTMLProps<T> {
    // If you want to use on:beforeinstallprompt
    oninviewchange?: (wariat: number) => { siema: string };
    // If you want to use myCustomAttribute={..} (note: all lowercase)
    // You can replace any with something more specific if you like
  }
}

```

**Comment by qelix** [comment]
Hey @maciekgrzybek,

sorry that it took me so long, I completely forgot about answering! Thanks for taking the time to figure this out! I'll see if I can do something about it and will report back :)

**Comment by maciekgrzybek** [comment]
This was way more complicated than I expected, but it's sorted now :) Closing this PR, but @qelix thanks a lot for help :)

**Pull request closed without merging**
